services:
  mongodb:
    image: mongo:latest
    container_name: cuida_caucaia_mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_INIT_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - cuida_caucaia_mongodb_data:/data/db

volumes:
  cuida_caucaia_mongodb_data:
