[project]
name = "api"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "nayetdet", email = "jpmoreiracampos21@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aioconsole>=0.8.1",
    "apscheduler>=3.11.0",
    "beanie>=2.0.0",
    "camoufox[geoip]>=0.4.11",
    "fastapi[standard]>=0.117.1",
    "motor>=3.7.1",
    "playwright>=1.55.0",
]

[project.scripts]
api = "api:main"

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
